services:
  app:
    build: .
    # ports:
    #   - 3000:3000
    restart: unless-stopped 
    tty: true
    depends_on:
      - db
      - redis

  db:
    image: postgres:16-alpine
    # ports:
    #   - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjsapp
      - TZ=Europe/Prague
    volumes:
      - db:/var/lib/postgres
    restart: unless-stopped 
    tty: true

  redis:
    image: redis:7.2.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    restart: unless-stopped
    tty: true


volumes:
  db:
  redis:
